// src/wc/components/navbar/index.js
const template = document.createElement("template");

template.innerHTML = `
  <style>
    :host {
      display: grid;

      grid-template-areas:
        "close-btn brand"
        "nav nav"
        "nav-right nav-right";

      grid-template-columns: auto 1fr;
      grid-template-rows: auto auto auto;

      background-color: var(--color-bgcolor);
      border-bottom: var(--border) solid var(--color-gray-300) !important;
    }

    :host([hide-brand]) {
      grid-template-areas:
        "close-btn spacer"
        "nav nav"
        "nav-right nav-right";

        grid-template-columns: auto 1fr;
        grid-template-rows: auto auto auto;
    }

    ::slotted([slot=brand]) {
      grid-area: brand;
      align-self: center;
    }

    div {
      grid-area: close-btn;
      align-self: center;
      margin-left: var(--m-4);
      margin-right: var(--m-4);
    }

    :host([hide-brand]) ::slotted([slot=brand]) {
      display: none;
    }

    button {
      background: 0;
      border: var(--border) solid var(--color-transparent);
      border-radius: var(--rounded);
      fill: var(--color-fgcolor);
      padding: var(--p-1) var(--p-2);
      margin-top: var(--m-2);
      margin-bottom: var(--m-2);
      cursor: pointer;
    }

    button:hover,
    button:focus,
    button:active,
    :host([mobile-menu-open]) button {
      outline: none;
      border-color: var(--color-gray-300);
      background-color: var(--color-gray-100);
    }

    ::slotted([slot=nav]) {
      grid-area: nav;
    }

    ::slotted([slot=nav-right]) {
      grid-area: nav-right;
    }

    ::slotted([slot=nav]),
    ::slotted([slot=nav-right]) {
      display: none;
      align-self: center;
      border-top: var(--border) solid var(--color-gray-300) !important;
      padding-top: var(--p-4);
      padding-bottom: var(--p-4);
      height: var(--h-full);
    }

    :host([mobile-menu-open]) ::slotted([slot=nav]),
    :host([mobile-menu-open]) ::slotted([slot=nav-right]) {
      display: block;
    }

    @media screen and (min-width: 768px) {
      :host {
        display: grid;
        gap: var(--p-4);

        grid-template-areas:
          "brand nav nav-right";

        grid-template-columns: auto 1fr auto;
        grid-template-rows: 1fr;

        background-color: var(--color-bgcolor);
        border-bottom: var(--border) solid var(--color-gray-300) !important;
        padding-left: var(--p-8);
        padding-right: var(--p-8);
      }

      :host([hide-brand]) {
        grid-template-areas:
          "nav nav-right";

        grid-template-columns: 1fr auto;
        grid-template-rows: 1fr;
      }

      ::slotted([slot=brand]) {
        padding: var(--p-0);
      }

      ::slotted([slot=nav]),
      ::slotted([slot=nav-right]) {
        display: flex;
        align-items: stretch;
        border: 0 !important;
        padding-top: var(--p-0);
        padding-bottom: var(--p-0);
      }

      :host([mobile-menu-open]) ::slotted([slot=nav]),
      :host([mobile-menu-open]) ::slotted([slot=nav-right]) {
        display: flex;
      }

      div {
        display: none;
      }
    }
  </style>
  <slot name="brand"></slot>
  <div>
    <button>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path class="heroicon-ui" d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"/></svg>
    </button>
  </div>
  <slot name="nav"></slot>
  <slot name="nav-right"></slot>
`;

class Component extends HTMLElement {
  constructor() {
    super();
    this._root = this.attachShadow({ mode: "open" });
  }

  connectedCallback() {
    this._root.appendChild(template.content.cloneNode(true));

    this._toggleFn = this._toggle.bind(this);
    this._closeFn = this._close.bind(this);

    this.$menuBtn = this._root.querySelector("button");
    this.$menuBtn.addEventListener("click", this._toggleFn);
    this.$nav = this._root.querySelector('slot[name="nav"]');
    this.$nav.addEventListener("click", this._closeFn);
    this.$navRight = this._root.querySelector('slot[name="nav-right"]');
    this.$navRight.addEventListener("click", this._closeFn);
  }

  disconnectedCallback() {
    this.$menuBtn.removeEventListener("click", this._toggleFn);
  }

  _toggle() {
    this.mobileMenuOpen = !this.mobileMenuOpen;
  }

  _close() {
    this.mobileMenuOpen = false;
  }

  static get observedAttributes() {
    return ["mobile-menu-open"];
  }

  set mobileMenuOpen(val) {
    if (val) {
      this.setAttribute("mobile-menu-open", "");
    } else {
      this.removeAttribute("mobile-menu-open");
    }
  }

  get mobileMenuOpen() {
    return this.hasAttribute("mobile-menu-open");
  }
}

customElements.define("sds-navbar", Component);

// simple-design-system/components/Navbar/Navbar.vue
<template>
  <div
    class="sds-navbar"
    :mobile-menu-open="mobileMenuOpen"
    :hide-brand="!hasBrandSlot"
  >
    <div v-if="hasBrandSlot" class="brand">
      <slot name="brand" />
    </div>
    <div class="menu-wrapper">
      <button id="navbarMenuButton" @click="toggle">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 24 24"
          width="24"
          height="24"
        >
          <path
            class="heroicon-ui"
            d="M4 5h16a1 1 0 0 1 0 2H4a1 1 0 1 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2zm0 6h16a1 1 0 0 1 0 2H4a1 1 0 0 1 0-2z"
          />
        </svg>
      </button>
    </div>
    <nav
      v-if="hasNavLeftSlot"
      class="nav-left"
      :class="[navClass]"
      @click.stop="close"
    >
      <slot name="nav" aria-labelledby="navbarMenuButton" />
    </nav>
    <nav
      v-if="hasNavRightSlot"
      class="nav-right"
      :class="[navRightClass]"
      @click.stop="close"
    >
      <slot name="nav-right" aria-labelledby="navbarMenuButton" />
    </nav>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "Navbar",
  props: {
    value: {
      type: Boolean,
      default: false,
    },
    navClass: {
      type: String,
      default: "",
    },
    navRightClass: {
      type: String,
      default: "",
    },
  },
  computed: {
    mobileMenuOpen: {
      get(): Boolean {
        return this.value;
      },
      set(val): any {
        this.$emit("input", val);
      },
    },
    hasBrandSlot(): Boolean {
      return !!this.$slots.brand;
    },
    hasNavLeftSlot(): Boolean {
      return !!this.$slots.nav;
    },
    hasNavRightSlot(): Boolean {
      return !!this.$slots["nav-right"];
    },
  },
  mounted() {
    document.addEventListener("keyup", this.handleEscKey);
  },
  destroyed() {
    document.removeEventListener("keyup", this.handleEscKey);
  },
  methods: {
    handleEscKey(e: KeyboardEvent) {
      if (e.keyCode === 27) {
        this.close();
      }
    },
    toggle() {
      this.mobileMenuOpen = !this.mobileMenuOpen;
    },
    close() {
      this.mobileMenuOpen = false;
    },
  },
});
</script>

<style lang="postcss" scoped>
.sds-navbar {
  @apply grid bg-bgcolor;

  grid-template-areas:
    "close-btn brand"
    "nav nav"
    "nav-right nav-right";

  grid-template-columns: auto 1fr;
  grid-template-rows: auto auto auto;
}

.sds-navbar[hide-brand] {
  grid-template-areas:
    "close-btn spacer"
    "nav nav"
    "nav-right nav-right";

  grid-template-columns: auto 1fr;
  grid-template-rows: auto auto auto;
}

.brand {
  @apply self-center;
  grid-area: brand;
}

.menu-wrapper {
  @apply self-center my-auto mx-2;
  grid-area: close-btn;
}

.sds-navbar[hide-brand] .brand {
  @apply hidden;
}

#navbarMenuButton {
  @apply bg-transparent border-transparent rounded p-1 my-2 h-10 w-10 cursor-pointer;
  fill: theme("colors.fgcolor");
}

#navbarMenuButton svg {
  @apply w-6 h-6 m-auto;
}

#navbarMenuButton:hover,
#navbarMenuButton:focus,
#navbarMenuButton:active,
.navbar[mobile-menu-open] #navbarMenuButton {
  @apply outline-none bg-gray-100 rounded-full;
}

#navbarMenuButton:active {
  filter: brightness(85%);
}

.nav-left {
  grid-area: nav;
}

.nav-right {
  grid-area: nav-right;
}

.nav-left,
.nav-right {
  @apply hidden self-center border-t p-4 h-full;
}

.sds-navbar[mobile-menu-open] .nav-left,
.sds-navbar[mobile-menu-open] .nav-right {
  @apply block;
}

@screen md {
  .sds-navbar {
    @apply grid gap-4 px-8;

    grid-template-areas: "brand nav nav-right";
    grid-template-columns: auto 1fr auto;
    grid-template-rows: 1fr;
  }

  .sds-navbar[hide-brand] {
    grid-template-areas: "nav nav-right";
    grid-template-columns: 1fr auto;
    grid-template-rows: 1fr;
  }

  .brand {
    @apply p-0;
  }

  .nav-left,
  .nav-right {
    @apply grid grid-flow-col border-0 p-0;
    grid-auto-columns: min-content;
  }

  .sds-navbar[mobile-menu-open] .nav-left,
  .sds-navbar[mobile-menu-open] .nav-right {
    @apply grid;
  }

  .menu-wrapper {
    @apply hidden;
  }
}
</style>
