// simple-design-system/components/Card/Card.vue
<template>
  <div class="sds-card" :type="type">
    <header v-if="hasHeaderSlot">
      <div class="header-inner">
        <div v-if="hasTitleSlot" class="title">
          <slot name="title" />
        </div>
        <div v-if="hasSubtitleSlot" class="subtitle">
          <slot name="subtitle" />
        </div>
      </div>
      <nav v-if="hasNavSlot" :class="[navClass]">
        <slot name="nav" />
      </nav>
    </header>
    <main>
      <slot />
    </main>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "Card",
  props: {
    navClass: {
      type: String,
      default: "",
    },
    type: {
      type: String,
      default: "",
    },
  },
  computed: {
    hasHeaderSlot(): Boolean {
      return this.hasTitleSlot || this.hasSubtitleSlot || this.hasNavSlot;
    },
    hasTitleSlot(): Boolean {
      return !!this.$slots.title;
    },
    hasSubtitleSlot(): Boolean {
      return !!this.$slots.subtitle;
    },
    hasNavSlot(): Boolean {
      return !!this.$slots.nav;
    },
  },
});
</script>

<style lang="postcss" scoped>
.sds-card {
  @apply block bg-gray-100;
}

.subtitle {
  @apply text-sm text-gray-500;
}

main {
  @apply p-4;
}

nav {
  @apply ml-auto grid grid-flow-col border-0 p-0;
  grid-auto-columns: min-content;
}

header {
  @apply flex py-3 px-4;
}

.header-inner {
  @apply self-center flex-grow;
}

.sds-card[type="simple"],
.sds-card[type="raised"],
.sds-card[type="accented"] {
  @apply border;

  & header {
    @apply border-b;
  }
}

.sds-card[type="raised"] {
  @apply shadow-lg rounded;
}

.sds-card[type="accented"] {
  @apply border-t-2;
  border-top-color: theme("colors.gray.900");
}
</style>

// simple-design-system/wc/card/index.js
const template = document.createElement("template");

template.innerHTML = `
  <style>
    :host {
      display: block;
      background-color: var(--color-bgcolor);
    }

    ::slotted([slot=subtitle]) {
      font-size: var(--text-sm);
      color: var(--color-gray-500);
    }

    ::slotted([slot=content]) {
      padding: var(--p-4);
    }

    ::slotted([slot=nav]) {
      margin-left: var(--m-auto);
      display: flex;
      justify-content: center;
      align-items: stretch;
    }

    header {
      display: flex;
      padding: var(--p-3) var(--p-4);
    }

    .header-inner {
      align-self: center;
      flex-grow: 1;
    }

    :host([type=simple]),
    :host([type=raised]) {
      border: var(--border) solid var(--color-border) !important;
    }

    :host([type=simple]) header,
    :host([type=raised]) header,
    :host([type=accented]) header {
      border-bottom: var(--border) solid var(--color-border);
    }

    :host([type=raised]) {
      box-shadow: var(--shadows);
      border-width: var(--border);
      border-radius: var(--rounded);
    }

    @media screen and (min-width: 640px) {
      :host([type=raised]) {
        border-radius: var(--rounded-lg);
      }
    }

    :host([type=accented]) header {
      border-top: var(--border-2) solid var(--color-fgcolor);
    }
  </style>
  <header part="header">
    <div class="header-inner" part="header-inner">
      <slot name="title"></slot>
      <slot name="subtitle"></slot>
    </div>
    <slot name="nav"></slot>
  </header>
  <slot name="content"></slot>
`;

class Component extends HTMLElement {
  constructor() {
    super();
    this._root = this.attachShadow({ mode: "open" });
  }

  connectedCallback() {
    this._root.appendChild(template.content.cloneNode(true));
  }

  disconnectedCallback() {}
}

customElements.define("sds-card", Component);
