// simple-design-system/components/LayoutStacked/LayoutStacked.vue
<template>
  <div class="sds-layout-stacked">
    <header v-if="hasHeaderSlot" :class="{ 'sticky-header': stickyHeader }">
      <slot name="header" />
    </header>
    <main>
      <slot />
    </main>
    <footer v-if="hasFooterSlot" :class="{ 'sticky-footer': stickyFooter }">
      <slot name="footer" />
    </footer>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({
  name: "LayoutStacked",
  props: {
    stickyHeader: {
      type: Boolean,
      default: false,
    },
    stickyFooter: {
      type: Boolean,
      default: false,
    },
  },
  computed: {
    hasHeaderSlot(): Boolean {
      return !!this.$slots.header;
    },
    hasFooterSlot(): Boolean {
      return !!this.$slots.footer;
    },
  },
});
</script>

<style lang="postcss" scoped>
.sds-layout-stacked {
  @apply grid min-h-screen w-full;

  grid-template-areas:
    "header"
    "content"
    "footer";

  grid-template-columns: 1fr;
  grid-template-rows: auto 1fr auto;
}

header {
  @apply z-30;
  grid-area: header;
}

main {
  grid-area: content;
}

footer {
  @apply z-20;
  grid-area: footer;
}

.sticky-header {
  @apply sticky top-0 shadow;
}

.sticky-footer {
  @apply sticky bottom-0 shadow;
}
</style>

// simple-design-system/wc/layout-stacked/index.js
const template = document.createElement("template");

template.innerHTML = `
  <style>
    :host {
      display: grid;

      grid-template-areas:
        "header"
        "content"
        "footer";

      grid-template-columns: 1fr;
      grid-template-rows: auto 1fr auto;

      min-height: var(--min-h-screen);
      width: var(--w-full);
    }

    ::slotted([slot=header]) {
      grid-area: header;
    }

    ::slotted([slot=content]) {
      grid-area: content;
    }

    ::slotted([slot=footer]) {
      grid-area: footer;
    }
  </style>
  <slot name="header"></slot>
  <slot name="content"></slot>
  <slot name="footer"></slot>
`;

class Component extends HTMLElement {
  constructor() {
    super();
    this._root = this.attachShadow({ mode: "open" });
  }

  connectedCallback() {
    this._root.appendChild(template.content.cloneNode(true));
  }

  disconnectedCallback() {}
}

customElements.define("sds-layout-stacked", Component);
